//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRSF_Binding : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean LeftTriggerClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftTriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftTouchpadPosition
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftTouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGripClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftGripClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftMenuClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftMenuClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightTriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGripClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightGripClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightTouchpadPosition
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightTouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTouchpadClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftTouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTouchpadClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightTouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightMenu
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTouchpadTouch
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightTouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTouchpadTouch
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftTouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Single RightTriggerPull
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightTriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Single LeftTriggerPull
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftTriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftPose
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightPose
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean YClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_YClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean XClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_XClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean AClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_AClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean BClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_BClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration LeftHaptic
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_LeftHaptic;
            }
        }
        
        public virtual SteamVR_Action_Vibration RightHaptic
        {
            get
            {
                return SteamVR_Actions.vRSF_Binding_RightHaptic;
            }
        }
    }
}
