//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRSF_Vive : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean LeftTriggerClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftTriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftTouchpadPosition
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftTouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGrip
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftMenu
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightTriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrip
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightGrip;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightTouchpadPosition
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightTouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTouchpadClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftTouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTouchpadClick
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightTouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightMenu
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTouchpadTouch
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightTouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTouchpadTouch
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftTouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Single RightTriggerPull
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightTriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Single LeftTriggerPull
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftTriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftPose
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightPose
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightPose;
            }
        }
        
        public virtual SteamVR_Action_Vibration LeftHaptic
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_LeftHaptic;
            }
        }
        
        public virtual SteamVR_Action_Vibration RightHaptic
        {
            get
            {
                return SteamVR_Actions.vRSF_Vive_RightHaptic;
            }
        }
    }
}
